### PR TITLE
fix: support fee calculation for Bifrost

### PR DESCRIPTION
**Pull request by ark930**

### CODE REVIEW

**Comment by TarikGul** [comment]
Looks like it needs a `yarn lint --fix`

**Comment by ark930** [comment]
@TarikGul My mistake, already fixed.

**Review by TarikGul — APPROVED** [review]
> @TarikGul My mistake, already fixed.

No Worries at all :)

lgtm!

**Review by emostov — APPROVED** [review]

**Comment by emostov** [comment]
@TarikGul  - should we have a CI job that generates `calc/pkg/calc_bg.wasm` to make sure its inline with exactly what gets merged?

**Comment by TarikGul** [comment]
> @TarikGul - should we have a CI job that generates `calc/pkg/calc_bg.wasm` to make sure its inline with exactly what gets merged?

Yea I was just thinking the same thing since I always recompile it after these PR's are merged. I agree though, it would enforce consistency on the build.

**Pull request merged**
