### PR TITLE
fix(deps): update polkadot-js/api, and rxjs

### PR DESCRIPTION
**Pull request by TarikGul**
Updates deps to the following:

    "@polkadot/api": "^7.6.1",
    "rxjs": "^7.5.2",

### CODE REVIEW

**Comment by TarikGul** [comment]
This introduces a warning every time a new runtime is queried but wont appear again once its cached:

```
2022-01-31 23:12:45 warn: ABLEREGISTRY: Unable to determine runtime Call type, cannot inspect sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic
2022-01-31 23:12:45 warn: ABLEREGISTRY: Unable to determine runtime Event type, cannot inspect frame_system::EventRecord
```

**Comment by niklasad1** [comment]
> This introduces a warning every time a new runtime is queried but wont appear again once its cached:

Have you filed an issue upstream? However, it's just a warn shouldn't be a big deal I suppose.

**Review by niklasad1 — APPROVED** [review]

**Comment by TarikGul** [comment]
> > This introduces a warning every time a new runtime is queried but wont appear again once its cached:
> 
> Have you filed an issue upstream? However, it's just a warn shouldn't be a big deal I suppose.

So I believe this is already known, as it's checking parachains metadata which explains why it only warns for relay chains. But that being said, it should be logging `PORTABLEREGISTRY` instead of `ABLEREGISTRY` which i'll report.

**Review by jsdw — APPROVED** [review]

**Comment by TarikGul** [comment]
The warning's are still going to be there, but after doing some extensive testing, and reading the code, this is a non issue so I am merging. I will follow up in polkadot-js api as well.

**Pull request merged**
