### PR TITLE
fix: enable experimental trace endpoints on polkadot

### PR DESCRIPTION
**Pull request by TarikGul**
cc:/ @emostov 

Enables the tracing endpoints for polkadot.

### CODE REVIEW

**Comment by emostov** [comment]
What is the motivation? Can we just instruct people to add this on their own?

**Comment by Imod7** [comment]
I did the change locally (added the `BlocksTrace` controller for polkadot), run a polkadot node with flag `--unsafe-rpc-external` but still I cannot see the `trace` endpoints on sidecar. So I guess there is also another change that I need to do in the node level ?

**Comment by TarikGul** [comment]
> I did the change locally (added the `BlocksTrace` controller for polkadot), run a polkadot node with flag `--unsafe-rpc-external` but still I cannot see the `trace` endpoints on sidecar. So I guess there is also another change that I need to do in the node level ?

I sanity checked this PR before pushing it up and the traces endpoints worked. Did you use `yarn build` to recompile the code, or are you using `yarn dev`?

**Comment by Imod7** [comment]
I run a polkadot node with this command : 
`./target/release/polkadot --chain=polkadot-dev --tmp  --rpc-cors=all --alice --unsafe-rpc-external`

Then in sidecar I run
`yarn build`

**Comment by TarikGul** [comment]
> 

So it should actually be 
`yarn build`
`yarn start`

**Review by emostov — APPROVED** [review]

**Review by 0xslipk — APPROVED** [review]
LGTM

**Pull request merged**
