### PR TITLE
fix: add fee calculation support and block weights for Astar network

### PR DESCRIPTION
**Pull request by hoonsubin**
This PR adds a controller and metadata consts for Astar network.

### CODE REVIEW

**Comment by TarikGul** [comment]
Looks good overall, I will give it a local run later as well. 
Just need to sign the CLA, in order to have the CI pass.

**Review by TarikGul — APPROVED** [review]
lgtm 👍 Just needs the CLA

**Comment by hoonsubin** [comment]
> lgtm 👍 Just needs the CLA

Me and @akru already signed the cla, but the CI status doesn't seem to change. Any fixes?

**Comment by joao-paulo-parity** [comment]
> > lgtm +1 Just needs the CLA
> 
> Me and @akru already signed the cla, but the CI status doesn't seem to change. Any fixes?

We track the CLA signatures by the GitHub user id. @akru of GitHub user id 786394 (https://api.github.com/users/akru) has a signature for the **old** revision of the CLA which was replaced by the **new** revision since 2020. Please sign the latest revision at https://cla.parity.io/sign_cla/786394/3 and ping me in case the status does not change.

**Comment by akru** [comment]
@joao-paulo-parity done

**Comment by TarikGul** [comment]
@akru @hoonsubin Just a heads up when this goes in, it will be part of next weeks release! (Most likely tuesday).

**Review by emostov — APPROVED** [review]

**Pull request merged**
