### PR TITLE
ci: Update runner tag to `linux-docker`

### PR DESCRIPTION
**Pull request by oleg-plakida**

### CODE REVIEW

**Review by TarikGul — APPROVED** [review]

**Comment by TarikGul** [comment]
The only thing would be when this is emerged is to ensure that merge commit is the same as the title ie. conventional commit.

**Review by Imod7 — APPROVED** [review]

**Review by alvicsam — APPROVED** [review]

**Comment by oleg-plakida** [comment]
That was premature. I might revert it later because of changed paradigm.

**Comment by oleg-plakida** [comment]
No worries. It won't affect ci. But i need to optimize it. Mb will make another PR.

**Comment by TarikGul** [comment]
> No worries. It won't affect ci. But i need to optimize it. Mb will make another PR.

That was my b as well (I should ask if its good to merge just in case). That being said thank so much for everything!

**Pull request merged**
