### PR TITLE
feat: Support Dock's multiplier & add Dock controller config

### PR DESCRIPTION
**Pull request by lovesh**
Signed-off-by: lovesh <lovesh.bond@gmail.com>

### CODE REVIEW

**Comment by lovesh** [comment]
I changed the `calc` package and thus upgraded its version to 0.1.3 and specified that in package.json as well. Should I not do that?

**Comment by emostov** [comment]
Thank you for the PR! I will pull this down within the next to try it out and make sure everything works.

**Comment by emostov** [comment]
I pushed to your branch and linked the calc package locally so it can be tested. However I couldn't find an index of Dock blocks for either network so I could not find any blocks to view that have transactions just to do a sanity check. 

Do you know of blocks in both networks that have transactions we can do a sanity check with for the calc package updates? Once we can do sanity checks we can then revert the local calc package setup and merge.

Other notes:

- There is the following complaint from polkadot-js in the console: ` METADATA: Unknown types found, no types for Bonus`. I bumped dependencies to see if Dock api types where updated in the `@polkadot/apps-config`, but that warning still appears.

- If Dock expects users for Sidecar I would highly suggest setting up a controller config as detailed in the [CHAIN_INTEGRATION guide](https://github.com/paritytech/substrate-api-sidecar/blob/master/CHAIN_INTEGRATION.md). For example, I noticed that none of the staking endpoints work so either modifying or disabling them would improve experience for users. I would be happy to help with that cc @dvdplm @joepetrowski

**Comment by lovesh** [comment]
Thanks @emostov. 

> Do you know of blocks in both networks that have transactions we can do a sanity check with for the calc package updates?

https://fe.dock.io/#/explorer/query/0xfb2003a3be82b2e03f14f1450c4545ace6f26be44dbbcb6debdcd6ca3b25636e and https://fe.dock.io/?rpc=wss%3A%2F%2Fdanforth-1.dock.io#/explorer/query/0x0c3b9a4f1f420a66c464571ceacff9bd6f6f51baee0ef9046a5b46f19d11c51f.

> There is the following complaint from polkadot-js in the console: METADATA: Unknown types found, no types for Bonus. I bumped dependencies to see if Dock api types where updated in the @polkadot/apps-config, but that warning still appears.

The types had changed. I've raised a [PR](https://github.com/polkadot-js/apps/pull/4219).

> If Dock expects users for Sidecar I would highly suggest setting up a controller config as detailed in the CHAIN_INTEGRATION guide.

I will check this. Thanks for the reference.

**Comment by lovesh** [comment]
Updated controllers [here](https://github.com/paritytech/substrate-api-sidecar/pull/365/commits/00919e5b105693e740ad4fd5352f1a7ba7fe7275).

**Review by emostov — APPROVED** [review]
Looks good! Just gonna ask for another set of eyes to review and we should be good  to merge.

Notes to other reviewers:
- I bumped deps, which resulted in needing to remove `typesRpc` import from @polkadot/apps-config. It appears the structure of exports there has changed and custom RPC defs come through the other exports now.
- In order to fully try out this branch locally one will need to replace `   "@substrate/calc": "^0.1.2",` with `"@substrate/calc": "file:./calc/pkg"`, in the `package.json` `dependencies` section.
- ran `build.sh` in calc and removed the .gitignore for the README.md so the `pkg` will have the standard NPM structure
- After this PR is merged an updated version of calc will be published (by me) and Sidecar will need a PR that updates the lockfile (#366)

**Review by niklasad1 — APPROVED** [review]
LGTM

**Comment by lovesh** [comment]
Thank you!

**Pull request merged**
