### PR TITLE
chore(release): 9.1.0

### PR DESCRIPTION
**Pull request by jsdw**
* feat: add /blocks/:number/header, and /blocks/head/header ([615](https://github.com/paritytech/substrate-api-sidecar/pull/615)) ([b7c2818](https://github.com/paritytech/substrate-api-sidecar/commit/b7c2818c57718526265f8104d9979a3cca127e3e))
* feat: Basic support for H160 and H256 accounts. ([596](https://github.com/paritytech/substrate-api-sidecar/pull/596)) ([bddc2a2](https://github.com/paritytech/substrate-api-sidecar/commit/bddc2a28c0477126a5aea4418188dedbf483e6d6))
* Update @polkadot/api to get the latest substrate specific upgrades.

### Bug Fixes

* fix: rewrite sidecar e2e script ([618](https://github.com/paritytech/substrate-api-sidecar/pull/618)) ([423574e](https://github.com/paritytech/substrate-api-sidecar/commit/423574e5db9828be6bb3f7721302829b1cd0661c))

### CODE REVIEW

**Review by TarikGul — APPROVED** [review]
LGTM, thank you!

**Comment by jsdw** [comment]
@TarikGul I did a force-push to tidy up the commit history just incase you checked it out; I was obviously not quick enough to avoid it being spotted here :D

**Comment by TarikGul** [comment]
@jsdw No worries at all :), thanks for the fix!

**Review by insipx — APPROVED** [review]
LGTM!

**Pull request merged**
