### PR TITLE
fix: support fee calculation for BifrostPolkadot

### PR DESCRIPTION
**Pull request by hqwangningbo**

### CODE REVIEW

**Comment by TarikGul** [comment]
Hey @hqwangningbo, Thanks for the contribution. This is my bad as I need to remove the guide for adding fee calculation. But `@substrate/calc` calcFee is no longer supported in Sidecar. This is because `weight_to_fee` and `length_to_fee` is no longer exposed in substrate. We are working to expand the algorithm to support all chains fees by default without anyone having to add their fee config. The following PR https://github.com/paritytech/substrate-api-sidecar/pull/974 can and discussion can be seen here. 

I will leave this PR up if you still want the config for the controllers in, but if you want accurate partialFee abstraction, for now it is advised to use `?feeByEvent=true` query param for `/blocks`. Let me know if you still want it in.

**Comment by hqwangningbo** [comment]
Hey @TarikGul,thank you for your work. I understand 😊

**Comment by TarikGul** [comment]
@hqwangningbo, if you revert the changes in `calc` we can still push this in with the Bifrost controller configs. :)

**Comment by hqwangningbo** [comment]
> @hqwangningbo, if you revert the changes in `calc` we can still push this in with the Bifrost controller configs. :)

Hey @TarikGul, I have updated it.

**Review by TarikGul — APPROVED** [review]

**Comment by TarikGul** [comment]
LGTM, @hqwangningbo is there an active node for bifrost_polkadot right now to double check the specName?

**Comment by hqwangningbo** [comment]
> LGTM, @hqwangningbo is there an active node for bifrost_polkadot right now to double check the specName?

yes , we have😊.  wss://hk.p.bifrost-rpc.liebi.com/ws

**Review by niklasad1 — APPROVED** [review]

**Pull request merged**
